export enum actionTypes {
  UI_LOADING = 'UI_LOADING',
  CREATE_CARD = 'CREATE_CARD',
  INIT_CARDS = 'INIT_CARDS',
  SELECT_CARD = 'SELECT_CARD',
  DESELECT_CARD = 'DESELECT_CARD',
  UPDATE_CARD = 'UPDATE_CARD',
  MOVE_CARD = 'MOVE_CARD',
  SEARCH_CARDS = 'SEARCH_CARDS'
}
